version: '3.7'

services:
  node:
    container_name: api-gateway
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/app
    command: npm start

   