# version: '3.7'

# ##edited
# services:
#  nginx_load_balancer_gateway:
#     image: nginx
#     volumes:
#       - './nginx/default.conf:/etc/nginx/nginx.conf'
#     ports:
#       - 8069:85

#   api_gateway1:
#     build: ./
#     ports:
#       - APPID=3333
#     volumes:
#       - .:/app
#     command: npm start
#     networks:
#       - microservice
  # api_gateway2:
  #   build: ./
  #   ports:
  #     - APPID=2222
  #   volumes:
  #     - .:/app
  #   command: npm start
  #   networks:
  #     - microservice
  # container_name1:
  #   build: ./
  #   ports:
  #     - APPID=1111
  #   volumes:
  #     - .:/app
  #   command: npm start
  #   networks:
  #     - microservice
      

# networks:
#   microservice:


version: '3'
services:
  nginx_load_balancer:
    image: nginx
    volumes:
      - './nginx/default.conf:/etc/nginx/nginx.conf'
    ports:
      - '8069:85'
    networks:
      - microservice
  api_gateway1:
    build: ./
    environment: 
      - APPID=3333
    networks:
      - microservice
  api_gateway2:
    build: ./
    environment: 
      - APPID=2222
    networks:
      - microservice
  api_gateway3:
    build: ./
    environment: 
      - APPID=9999
    networks:
      - microservice
      


networks:
  microservice:
  #     - APPID=3333
  # app4:
  #   image: node-app
  #   environment: 
  #     - APPID=4444
  # app5:
  #   image: node-app
  #   environment: 
  #     - APPID=5555
    
   