version: '3.7'

services:
  node:
    container_name: api-gateway
    image: 210314021403/api-gateway-service
    ports:
      - 3333:3333
    volumes:
      - .:/app
    command: npm start
    networks:
      - microservice

networks:
  microservice:
   