version: '3.7'

services:
  node:
    container_name: api-gateway
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3333:3333
    volumes:
      - .:/app
    command: npm start
    networks:
      - microservice

networks:
  microservice:
   