version: '3.7'

##edited
services:
  node:
    container_name: api-gateway
    build: ./
    ports:
      - 3333:3333
    volumes:
      - .:/app
    command: npm start
    networks:
      - microservice

networks:
  microservice:
   