declare module 'mf-products/ProductsModule'
declare module 'mf-products/ProductDetailModule'
declare module 'mf-products/CreateProductModule'
declare module 'mf-authentication/AuthenticationModule'
declare module 'mf-shopping-cart/ShoppingCartModule'
declare module 'mf-shopping-cart/CheckoutModule'
declare module 'mf-contact/ContactModule'